<template>
  <div>
    <div class="d-flex justify-between align-center mb-4">
      <!-- Heading -->
      <h3 class="shrink-0">Asset Demobilizations</h3>

      <!-- Search -->
      <VTextField
        v-model="search"
        placeholder="Search by User, Custodian or Description..."
        density="comfortable"
        variant="outlined"
        hide-details
        class="mx-4 flex-grow-1"
        @keyup.enter="fetchDemobilizations"
      />

      <!-- Create Button -->
      <VBtn
        color="primary"
        class="shrink-0"
        @click="$router.push('/dashboards/asset-demobilizations/create')"
      >
        Create Demobilization
      </VBtn>
    </div>

    <!-- Loading -->
    <p v-if="isLoading">Loading...</p>

    <!-- Error -->
    <p v-else-if="errorMessage" class="text-error">{{ errorMessage }}</p>

    <!-- Table -->
    <VDataTable
      v-else-if="demobilizations.length > 0"
      :headers="headers"
      :items="demobilizations"
      :items-per-page="10"
      :search="search"
    >
      <!-- Actions -->
      <template #item.actions="{ item }">
        <VMenu :close-on-content-click="true">
          <template #activator="{ props, isActive }">
            <VBtn
              v-bind="props"
              size="small"
              color="primary"
              variant="elevated"
              class="d-flex align-center gap-1"
            >
              Actions
              <VIcon :icon="isActive ? 'tabler-caret-up' : 'tabler-caret-down'" />
            </VBtn>
          </template>

          <VList density="compact">
            <VListItem @click="$router.push(`/dashboards/asset-demobilizations/detail/${item.id}`)">
              <template #prepend><VIcon icon="tabler-eye" /></template>
              <VListItemTitle>Detail</VListItemTitle>
            </VListItem>

          </VList>
        </VMenu>
      </template>
    </VDataTable>

    <!-- Empty State -->
    <VCard v-else class="mt-6 pa-6 text-center" variant="tonal">
      <VCardTitle>No asset demobilizations found</VCardTitle>
      <VCardText>
        You don’t have any demobilizations yet. Create your first one to get started.
      </VCardText>
      <VBtn color="primary" @click="$router.push('/dashboards/asset-demobilizations/create')">
        Create Demobilization
      </VBtn>
    </VCard>
  </div>
</template>

<script setup>
import axios from "axios";
import { ref, onMounted } from "vue";
import {
  VBtn, VCard, VCardText, VCardTitle,
  VDataTable, VIcon, VList, VListItem,
  VListItemTitle, VMenu, VTextField
} from "vuetify/components";

const apiBaseUrl = import.meta.env.VITE_API_BASE_URL;

const demobilizations = ref([]);
const isLoading = ref(true);
const errorMessage = ref("");
const search = ref("");

const headers = [
  { title: "ID", key: "id" },
  { title: "Date", key: "date" },
  { title: "Generated By", key: "generated_by" }, // mapped field
  { title: "Custodian", key: "custodian" },       // mapped field
  { title: "Asset", key: "asset_display" },      // new mapped field
  { title: "Total Qty", key: "total_quantity_demobilized" },
  { title: "Remaining Qty", key: "remaining_quantity" },
  { title: "Actions", key: "actions", sortable: false },
];


/* ---------- Auth helper ---------- */
const getCookie = (name) => {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(";").shift();
  return null;
};

const getAuthHeaders = () => {
  const accessToken = getCookie("accessToken");
  if (!accessToken) throw new Error("Access token is missing.");
  return { Authorization: `Bearer ${decodeURIComponent(accessToken)}`, Accept: "application/json" };
};

/* ---------- Fetch Data ---------- */
const fetchDemobilizations = async () => {
  isLoading.value = true;
  errorMessage.value = "";
  try {
    const res = await axios.get(`${apiBaseUrl}/asset-demobilizations`, {
      headers: getAuthHeaders(),
      params: { search: search.value },
    });

    const list = Array.isArray(res?.data?.data) ? res.data.data : [];
    
    // Map nested fields
   demobilizations.value = list.map(d => ({
      ...d,
      generated_by: d.user ? `${d.user.user_code} — ${d.user.name}` : "",
      custodian: d.custodian ? `${d.custodian.user_code} — ${d.custodian.name}` : "",
      asset_display: d.asset ? `${d.asset.code} — ${d.asset.title}` : "",
    }));
        
  } catch (err) {
    console.error("Error fetching demobilizations:", err);
    errorMessage.value = err.response?.data?.message || "Failed to fetch demobilizations.";
  } finally {
    isLoading.value = false;
  }
};

/* ---------- Delete ---------- */
const deleteDemobilization = async (id) => {
  if (!confirm("Are you sure you want to delete this demobilization?")) return;

  try {
    await axios.delete(`${apiBaseUrl}/asset-demobilizations/${id}`, {
      headers: getAuthHeaders(),
    });
    demobilizations.value = demobilizations.value.filter(d => d.id !== id);
    alert("Demobilization deleted successfully!");
  } catch (err) {
    console.error("Error deleting demobilization:", err);
    alert(err.response?.data?.message || "Failed to delete demobilization.");
  }
};

onMounted(fetchDemobilizations);
</script>

<style>
.v-data-table { margin-block-start: 16px; }
.d-flex { display: flex; }
.justify-between { justify-content: space-between; }
.align-center { align-items: center; }
.text-error { color: #c62828; }
</style>
