<template>
  <div>
    <div class="d-flex justify-between align-center mb-4">
      <h3>Asset Demobilization Detail</h3>
      <VBtn color="primary" @click="$router.push('/dashboards/asset-demobilizations')">
        Back to List
      </VBtn>
    </div>

    <VCard v-if="isLoading" class="pa-6">
      <p>Loading...</p>
    </VCard>

    <VCard v-else-if="errorMessage" class="pa-6">
      <p class="text-error">{{ errorMessage }}</p>
    </VCard>

    <VCard v-else class="pa-6" outlined>
      <VRow>
        <VCol cols="12" md="6">
          <strong>Project:</strong> {{ assetDemobilization.project.project_code }} — {{ assetDemobilization.project.name }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Generated By:</strong> {{ assetDemobilization.user.user_code }} — {{ assetDemobilization.user.name }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Custodian:</strong> {{ assetDemobilization.custodian.user_code }} — {{ assetDemobilization.custodian.name }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Asset:</strong> {{ assetDemobilization.asset.code }} — {{ assetDemobilization.asset.title }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Total Quantity Demobilized:</strong> {{ assetDemobilization.total_quantity_demobilized }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Remaining Quantity:</strong> {{ assetDemobilization.remaining_quantity }}
        </VCol>

        <VCol cols="12" md="6">
          <strong>Date:</strong> {{ assetDemobilization.date }}
        </VCol>

        <VCol cols="12">
          <strong>Description:</strong>
          <p>{{ assetDemobilization.description || '-' }}</p>
        </VCol>
      </VRow>
    </VCard>
  </div>
</template>

<script setup>
import axios from 'axios'
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { VCard, VCol, VRow, VBtn } from 'vuetify/components'

const route = useRoute()
const router = useRouter()
const apiBaseUrl = import.meta.env.VITE_API_BASE_URL

const assetDemobilization = ref(null)
const isLoading = ref(true)
const errorMessage = ref('')

/* ---------- Auth helper ---------- */
const getCookie = (name) => {
  const value = `; ${document.cookie}`
  const parts = value.split(`; ${name}=`)
  if (parts.length === 2) return parts.pop().split(';').shift()
  return null
}

const getAuthHeaders = () => {
  const accessToken = getCookie('accessToken')
  if (!accessToken) throw new Error('Access token is missing.')
  return { Authorization: `Bearer ${decodeURIComponent(accessToken)}`, Accept: 'application/json' }
}

/* ---------- Fetch Single Asset Demobilization ---------- */
const fetchDemobilization = async () => {
  isLoading.value = true
  errorMessage.value = ''
  try {
    const res = await axios.get(`${apiBaseUrl}/asset-demobilizations/${route.params.id}`, {
      headers: getAuthHeaders(),
    })
    assetDemobilization.value = res.data
  } catch (err) {
    console.error('Error fetching demobilization:', err)
    errorMessage.value = err.response?.data?.message || 'Failed to fetch asset demobilization.'
  } finally {
    isLoading.value = false
  }
}

onMounted(fetchDemobilization)
</script>

<style scoped>
.mb-4 { margin-block-end: 16px; }
.d-flex { display: flex; }
.justify-between { justify-content: space-between; }
.align-center { align-items: center; }
.text-error { color: #c62828; }
</style>
